### ISSUE TITLE
Error can't authenticate

### ISSUE THREAD

**Issue by Pretzel0000** [DeKaN/pyboneco#1]
I follow the steps and it seems to connect but then get an authentication error.
`__.py

Choose between (1) pairing new device and (2) connecting existing device: 1
Scan results: 
1) 6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4: F235 (Pairing active = True)

Choose device to pair [1-1]: 1
Chosen device "F235" with address "6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4". Pairing active = True
INFO:pyboneco.auth:Setting nonce
Got new auth state: current=0, level=-1
INFO:pyboneco.auth:Processing auth response
INFO:pyboneco.auth:Changed auth level to 0
Got new auth state: current=1, level=0
Press button on device to confirm pairing
INFO:pyboneco.client:F235 (6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4): Press device button to confirm
Got new auth state: current=2, level=0
INFO:pyboneco.auth:Saving device key
Got new auth state: current=3, level=0
Got new auth state: current=2, level=0
INFO:pyboneco.auth:Processing auth response
INFO:pyboneco.auth:Changed auth level to 1
Got new auth state: current=9, level=1
Got new auth state: current=2, level=1
INFO:pyboneco.auth:Processing auth response
ERROR:pyboneco.auth:Auth error, current level remains 1
Got new auth state: current=-1, level=1
ERROR:pyboneco.client:F235 (6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4): Can't auth. Exiting

Press Enter for exit
`

**Comment by DeKaN** [comment]
Hi @Pretzel0000 
Looks like I missed that device sends multiple packets with auth data, just reproduced with my device

```
INFO:pyboneco.auth:Setting nonce
Got new auth state: current=0, level=-1
INFO:pyboneco.auth:Processing auth response
INFO:pyboneco.auth:Changed auth level to 0
Got new auth state: current=1, level=0
Press button on device to confirm pairing
INFO:pyboneco.client:W400 (<MAC>): Press device button to confirm
Got new auth state: current=2, level=0
INFO:pyboneco.auth:Saving device key
Got new auth state: current=3, level=0
Got new auth state: current=2, level=0
INFO:pyboneco.auth:Processing auth response
INFO:pyboneco.auth:Changed auth level to 1
Got new auth state: current=9, level=1
INFO:pyboneco.client:W400 (<MAC>): Auth finished. Exiting
Got new auth state: current=2, level=1
User's device name is W400
Device json data: {"address": "<MAC>", "name": "W400", "key": "<KEY>"}
INFO:pyboneco.auth:Setting nonce
Got new auth state: current=3, level=1
INFO:pyboneco.auth:Processing auth response
ERROR:pyboneco.auth:Auth error, current level remains 1
Got new auth state: current=-1, level=1
ERROR:pyboneco.client:W400 (<MAC>): Can't auth. Exiting
INFO:pyboneco.auth:Processing auth response
INFO:pyboneco.auth:Changed auth level to 1
Got new auth state: current=9, level=1
ERROR:pyboneco.client:41
Device info: {'_device_type': 2, '_device': <pyboneco.device.BonecoHumidifierDevice object at 0x000001FCFC6123C0>, '_fds_config_error': 0, '_fds_log_error': 0, '_fds_state_error': 0, '_no_water_error': 0, '_no_filter_error': 0, '_no_base_error': 0, '_fan_error': 0, '_hum_pack_error': 0, '_temp': 22, '_humidity': 24, '_particle_value': None, '_voc': None, '_serial_number': <REDACTED>, '_factory_number': 9999, '_software_version': '1.027', '_hardware_version': '1.0'}
Device state: {'_is_air_fan_device': False, '_has_service_operating_counter': False, '_operating_mode': <OperationMode.HUMIDIFIER: 1>, '_mode_status': <ModeStatus.CUSTOM: 0>, '_fan': 0, '_fan_mode': 0, '_timer': 0, '_always_history_active': 0, '_lock': 0, '_on_off': 0, '_DeviceState__unused': 0, '_target_humidity': 60, '_change_filter': 0, '_change_iss': 0, '_clean': 0, '_change_water': 0, '_reminder_filter_counter': None, '_reminder_iss_counter': None, '_reminder_clean_counter': None, '_reminder_filter_date': 0, '_reminder_iss_date': 1767628800, '_reminder_clean_date': 1737302400, '_on_off_timer_hours': 0, '_clean_mode_support': 0, '_on_off_timer_status': <TimerStatus.OFF: 0>, '_on_off_timer_minutes': 0, '_min_led_brightness': 5, '_max_led_brightness': 100}
Press Enter for exit
```

I'll add check for "packet for state has been processed"

**Comment by DeKaN** [comment]
@Pretzel0000 Can you check again with added fix?

**Comment by Pretzel0000** [comment]
@DeKaN Got it connected thank you!!! im just trying to figure out how to control it now 😂

**Comment by Pretzel0000** [comment]
@DeKaN Got it connected thank you!!! im just trying to figure out how to control it now 😂

**Comment by Pretzel0000** [comment]
sorry I am now getting this error INFO:pyboneco.client:F235 (6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4): Auth finished. Exiting
ERROR:pyboneco.client:Characteristic notification never started

**Comment by Pretzel0000** [comment]
INFO:pyboneco.client:F235 (6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4): Auth finished. Exiting
ERROR:pyboneco.client:Characteristic notification never started

**Comment by Pretzel0000** [comment]
Heres what I'm getting

```
//Users/thomastobin/Downloads/pyboneco/venv/bin/python /Users/thomastobin/Downloads/pyboneco/pyboneco/__main__.py
venvthomastobin@MacBook-Air pyboneco % /Users/thomastobin/Downloads/pyboneco/venv/bin/python /Users/thomastobin/Downlo
ads/pyboneco/pyboneco/__main__.py

Choose between (1) pairing new device and (2) connecting existing device: 1
Scan results: 
1) 6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4: F235 (Pairing active = True)

Choose device to pair [1-1]: 1
Chosen device "F235" with address "6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4". Pairing active = True
INFO:pyboneco.auth:Setting nonce
Got new auth state: current=0, level=-1
INFO:pyboneco.auth:Processing auth response
INFO:pyboneco.auth:Changed auth level to 0
Got new auth state: current=1, level=0
Press button on device to confirm pairing
INFO:pyboneco.client:F235 (6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4): Press device button to confirm
INFO:pyboneco.auth:Pairing confirmed
Got new auth state: current=2, level=0
INFO:pyboneco.auth:Saving device key
Got new auth state: current=3, level=0
INFO:pyboneco.auth:Processing auth response
INFO:pyboneco.auth:Changed auth level to 1
Got new auth state: current=9, level=1
INFO:pyboneco.client:F235 (6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4): Auth finished. Exiting
User's device name is Bubba Gump Fans & Co
Device json data: {"address": "6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4", "name": "F235", "key": "ed7ef45d95c17f70f5097bdb5a3bd031"}
Device info: {'_device_type': 12, '_device': <pyboneco.device.BonecoAirFanDevice object at 0x10143c2d0>, '_fds_config_error': 0, '_fds_log_error': 0, '_fds_state_error': 0, '_no_water_error': 0, '_no_filter_error': 0, '_no_base_error': 0, '_fan_error': 0, '_hum_pack_error': 0, '_temp': 0, '_humidity': 0, '_particle_value': 0, '_voc': 0, '_serial_number': 99999200214794, '_factory_number': 9999, '_software_version': '1.027', '_hardware_version': '1.0'}
Device state: {'_is_air_fan_device': True, '_has_service_operating_counter': False, '_operating_mode': <OperationMode.NONE: 0>, '_mode_status': <ModeStatus.CUSTOM: 0>, '_fan': 1, '_timer': 0, '_always_history_active': 0, '_lock': 0, '_on_off': 0, '_DeviceState__unused': 0, '_target_humidity': 0, '_change_filter': 0, '_change_iss': 0, '_clean': 0, '_change_water': 0, '_reminder_filter_counter': None, '_reminder_iss_counter': None, '_reminder_clean_counter': None, '_reminder_filter_date': 0, '_reminder_iss_date': 0, '_reminder_clean_date': 0, '_on_off_timer_hours': 0, '_clean_mode_support': 0, '_on_off_timer_status': <TimerStatus.OFF: 0>, '_on_off_timer_minutes': 0, '_min_led_brightness': 10, '_max_led_brightness': 100}
Press Enter for exit

```

**Comment by DeKaN** [comment]
As I see, you've got "device key". Can you try "connecting existing device" mode? Use json from line "Device json data"

**Comment by Pretzel0000** [comment]
comes back with the same 

```
/Users/thomastobin/Downloads/pyboneco/venv/bin/python /Users/thomastobin/Downloads/pyboneco/pyboneco/__main__.py
venvthomastobin@MacBook-Air pyboneco % /Users/thomastobin/Downloads/pyboneco/venv/bin/python /Users/thomastobin/Downlo
ads/pyboneco/pyboneco/__main__.py

Choose between (1) pairing new device and (2) connecting existing device: 2
Enter device json data
{"address": "6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4", "name": "F235", "key": "ed7ef45d95c17f70f5097bdb5a3bd031"}
INFO:pyboneco.auth:Setting nonce
INFO:pyboneco.auth:Processing auth response
INFO:pyboneco.auth:Changed auth level to 1
INFO:pyboneco.client:F235 (6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4): Auth finished. Exiting
ERROR:pyboneco.client:Characteristic notification never started
User's device name is Bubba Gump Fans & Co
Device json data: {"address": "6C7BAC08-5EEA-5157-80A4-FCEC0D080CC4", "name": "F235", "key": "ed7ef45d95c17f70f5097bdb5a3bd031"}
Device info: {'_device_type': 12, '_device': <pyboneco.device.BonecoAirFanDevice object at 0x10684c2d0>, '_fds_config_error': 0, '_fds_log_error': 0, '_fds_state_error': 0, '_no_water_error': 0, '_no_filter_error': 0, '_no_base_error': 0, '_fan_error': 0, '_hum_pack_error': 0, '_temp': 0, '_humidity': 0, '_particle_value': 0, '_voc': 0, '_serial_number': 99999200214794, '_factory_number': 9999, '_software_version': '1.027', '_hardware_version': '1.0'}
Device state: {'_is_air_fan_device': True, '_has_service_operating_counter': False, '_operating_mode': <OperationMode.NONE: 0>, '_mode_status': <ModeStatus.CUSTOM: 0>, '_fan': 1, '_timer': 0, '_always_history_active': 0, '_lock': 0, '_on_off': 0, '_DeviceState__unused': 0, '_target_humidity': 0, '_change_filter': 0, '_change_iss': 0, '_clean': 0, '_change_water': 0, '_reminder_filter_counter': None, '_reminder_iss_counter': None, '_reminder_clean_counter': None, '_reminder_filter_date': 0, '_reminder_iss_date': 0, '_reminder_clean_date': 0, '_on_off_timer_hours': 0, '_clean_mode_support': 0, '_on_off_timer_status': <TimerStatus.OFF: 0>, '_on_off_timer_minutes': 0, '_min_led_brightness': 10, '_max_led_brightness': 100}
Press Enter for exit

```

**Comment by DeKaN** [comment]
Fixed uncritical error, script works as I see in your logs

**Comment by Pretzel0000** [comment]
but its now saying `ERROR:pyboneco.client:Characteristic notification never started`

**Comment by Pretzel0000** [comment]
and still cant control the device

**Comment by DeKaN** [comment]
It's a library with API for getting/setting device state. You can use it to write your script to control a device.

just an example
```
scanned = await BonecoClient.find_boneco_devices()
device = next((x for x in scanned.keys() if x.address == "address_here"), None)
auth_data = BonecoAuth(device, "key_here")
bleak_client = BleakClient(address_or_ble_device=auth.device)
boneco_client = BonecoClient(bleak_client, auth)
try:
    await boneco_client.connect()
    state = await boneco_client.get_state()
    state.fan_level = DeviceState.AIR_FAN_DEVICE_FAN_MAX_VALUE
    state.max_led_brightness = 25
    await boneco_client.set_state(state)
except Exception as e:
    print(e)
finally:
    await boneco_client.disconnect()
```

**Comment by Pretzel0000** [comment]
Still can’t get it to work! I’ll try and play around with it a bit more! Thank you !!

**Comment by Pretzel0000** [comment]
Update got it working @DeKaN

**Comment by DeKaN** [comment]
Hi, @Pretzel0000 

Does your script work without `state._fan_mode = 0`?

**Comment by DeKaN** [comment]
As I know, this value is not used by devices "F225" and "F235". So, its value is ignored in state for your device
